parameters:
- name: runTimeParam
  displayName: Test Param Name
  default: Hello
  type: string

variables:
  - group: myVarGroup
  - name: vvv1
    value: vvv1

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "stage variable: $(vvv1)"
      echo "pipeline param: ${{ parameters.runTimeParam }}"
      echo "variable from project variable group: $(v1)"
      echo "secret from project variable group: $(secret1)"
      echo "pipeline variable: $(MyPipelineVariable)"
      echo "pipeline secret: $(MyPipelineSecret)"
      exit 1
  - task: CmdLine@2
    displayName: "Running Task with always() condition"
    condition: always()
    inputs:
      script: |
        echo "this script should run"
  - task: CmdLine@2
    displayName: "Running Task with failed() condition"
    condition: failed()
    inputs:
      script: |
        echo "this script should run"
  - task: CmdLine@2
    displayName: "Running Task with succeeded() condition"
    condition: succeeded()
    inputs:
      script: |
        echo "this script should not run"
