# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Test Param Name
  default: Hello
  type: string

variables:
  - group: myVarGroup
  - name: v1
    value: $[variables.v1]
  - name: vvv1
    value: vvv1

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(v1)
    echo $(vvv1)
    echo $[variables.v1]
  displayName: Test