# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: runTimeParam
  displayName: Test Param Name
  default: Hello
  type: string

variables:
  - group: myVarGroup
  - name: vvv1
    value: vvv1

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "stage variable: $(vvv1)"
      echo "pipeline param: ${{ parameters.runTimeParam }}"
      echo "variable from project variable group: $(v1)"
      echo "secret from project variable group: $(secret1)"
      echo "pipeline variable: $(MyPipelineVariable)"
      echo "pipeline secret: $(MyPipelineSecret)"