# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: runTimeParam
  displayName: Test Param Name
  default: Hello
  type: string

variables:
  - group: myVarGroup
  - name: vvv1
    value: vvv1

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "stage variable \$(vvv1): $(vvv1)"
      echo "pipeline param \${{ paramters.runTimeParam }}: ${{ parameters.runTimeParam }}"
      echo "pipeline variable group \$[ variables.v1 ] : $[ variables.v1 ]"
      echo "pipeline variable \$(MyPipelineVariable): $(MyPipelineVariable)"
      echo "pipeline secret \$(MyPipelineSecret): $(MyPipelineSecret)"