name: Test GitHub Actions (condtions)

on:
  push:
    branches: [ main ]
  issues:
    types: [ labeled ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-javascript-action@v1.1
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: issue labeled with "test"
      if: contains(github.event.issue.label.*.name, "test")
      uses: peter-evans/close-issue@v1.0.3
