# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set output test step
      id: test-output
      run: |
        echo "::set-output name=testVar1::Hello World"
        echo "::set-output name=testVar2::456"
    - name: Use output variables
      run: |
        echo ${{ steps.test-output.outputs.testVar1 }}
        echo ${{ steps.test-output.outputs.testVar2 }}
